apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todolist-keyvault
  labels: 
    azure.azureauthority.in: todo-list
    app: todo-list
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: da4012e5-f4d1-430a-8071-a70c43f93f1b
    keyvaultName: kvproject314
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c